// <auto-generated />
using System;
using LolTurnBase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LolTurnBase.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241002093756_CreatedFKRelationItemToChampion")]
    partial class CreatedFKRelationItemToChampion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LolTurnBase.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbillityPower")
                        .HasColumnType("integer");

                    b.Property<int>("Armor")
                        .HasColumnType("integer");

                    b.Property<int>("AttackDamage")
                        .HasColumnType("integer");

                    b.Property<int>("Health")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<int>("MagicResist")
                        .HasColumnType("integer");

                    b.Property<int>("Mana")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Champion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbillityPower = 15,
                            Armor = 10,
                            AttackDamage = 30,
                            Health = 300,
                            Level = 1,
                            MagicResist = 11,
                            Mana = 100,
                            Name = "Gragas"
                        },
                        new
                        {
                            Id = 2,
                            AbillityPower = 20,
                            Armor = 10,
                            AttackDamage = 30,
                            Health = 200,
                            Level = 1,
                            MagicResist = 12,
                            Mana = 200,
                            Name = "Ryze"
                        });
                });

            modelBuilder.Entity("LolTurnBase.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbillityPowerGained")
                        .HasColumnType("integer");

                    b.Property<int>("ArmorGained")
                        .HasColumnType("integer");

                    b.Property<int>("AttackDamageGained")
                        .HasColumnType("integer");

                    b.Property<int?>("ChampionID")
                        .HasColumnType("integer");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HealthGained")
                        .HasColumnType("integer");

                    b.Property<int>("MagicResitGained")
                        .HasColumnType("integer");

                    b.Property<int>("ManaGained")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChampionID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AbillityPowerGained = 20,
                            ArmorGained = 15,
                            AttackDamageGained = 30,
                            ChampionID = 1,
                            Cost = 999999,
                            Description = "Provides Random Stuff",
                            HealthGained = 100,
                            MagicResitGained = 100,
                            ManaGained = 100,
                            Name = "Allmighty"
                        });
                });

            modelBuilder.Entity("LolTurnBase.Models.Item", b =>
                {
                    b.HasOne("LolTurnBase.Models.Champion", "Champion")
                        .WithMany()
                        .HasForeignKey("ChampionID");

                    b.Navigation("Champion");
                });
#pragma warning restore 612, 618
        }
    }
}
